debtor.company.name=TCompany
debtor.country=SE
debtor.currency.dk=DKK
debtor.currency.se=SEK
debtor.currency.no=NOK
debtor.name=Main account
debtor.signed.Id=1825226354
debtor.agreement.id=117930424561
debtor.account.iban=SE1395000099601800174375
debtor.bic.dk=NDEADKKK
debtor.bic.no=NDEANOKK
debtor.bic.se=NDEASESS
#certificate.file.path=C:/Temp/pain/certi/Si_1825226354.p12
certificate.file.path=certi/Si_1825226354.p12
certificate.password=pstest
key.store.type=PKCS12
store.folder=C:/Temp/pain/output/file
wrap.file.exe=.war
signed.file.exe=.xml
record.separator=;